### ISSUE TITLE
Fix 'auto-correct' depreaction warning

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [runtastic/rubocop_runner#8]
RubcopRunner prints the following deprecation warning: `--auto-correct is deprecated; use --autocorrect instead.`

It should use the new `--autocorrect` parameter.

**Comment by Goltergaul** [comment]
@ThomasKoppensteiner there is a pr from someone about this already

**Comment by ThomasKoppensteiner** [comment]
#7
